### ISSUE TITLE
要是filter,map,reduce能像Java Stream链式调用就好了

### ISSUE THREAD

**Issue by xuning888** [skholee/generic-wheel#1]
`
type Stream struct {
	temp []any
}

func AsStream(sli []any) *Stream {
	return &Stream{temp: sli}
}

func (s *Stream) Filter(predicate func(a any) bool) *Stream {
	var sli []any
	for _, e := range s.temp {
		if predicate(e) {
			sli = append(sli, e)
		}
	}
	s.temp = sli
	return s
}
`
一点点先发，不太懂go

**Comment by skholee** [comment]
由于go泛型设计中method不支持类型参数，故而暂无法通过较好地通过stream进行函数式链式调用，如：Stream.Filter(xx).Map(xx)...  。

type Stream[T any] struct {

}

func (s *Stream[T]) Filter(p func(T) bool) Stream[T] {
...
}

func (s *Stream[T]) Map[D any](f func(T) D) Stream[D] {
// 期望如此，但会提示：method must have no type parameters
}

https://go.dev/doc/faq#generic_methods

**Comment by xuning888** [comment]
好的，明白了，谢谢小哥
